blank_issues_enabled: false
contact_links:
  - name: Contributing guide
    url: https://github.com/freestackhq/selfhosted/blob/main/CONTRIBUTING.md
    about: Read the contributing guide before opening an issue
